unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix

set -g mouse on

set -g default-terminal "xterm-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'   # Enable italics.
set-option -g history-limit 10000
set-option -g status-interval 1
set-option -g status-left-length 200
set-option -g status-left "#[fg=colour214] [#{session_name}] "
set -g status-justify centre
set-window-option -g window-status-format " #I:#W"
set-window-option -g window-status-current-style bg=colour52  # Backgrounc style labeling current window.
set-window-option -g mode-style 'fg=white'
set -g status-right-length 200
set-option -g status-right " #[fg=colour14,bg=default]%a %l:%M:%S %p#[default]  #[fg=colour74]%Y-%m-%d "
set -g status-style bg='#282a36'  # '#b3ae83'
set -g mode-style 'fg=white,bg=blue' # Change highlight colour

bind-key c command-prompt -p "window name:" "new-window; rename-window '%%'"

set -s set-clipboard on  # Allow applications inside tmux to set the clipboard.

# Need to run `git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm` to download tpm
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'erikw/tmux-powerline'

set -g @plugin 'tmux-plugins/tmux-yank' # On MacOS, need to do `brew install reattach-to-user-namespace` too

## Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
